apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-appli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-appli
  template:
    metadata:
      labels:
        app: mon-appli
    spec:
      containers:
        - name: mon-conteneur
          image: tabelsichahd/mon-image:latest
          imagePullPolicy: Always  # ← CHANGEMENT ICI
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mon-appli-service
spec:
  selector:
    app: mon-appli
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort